Add a couple of missing wireit dependency graph edges (#4253)
Doesn't directly address
https://github.com/breadboard-ai/breadboard/issues/4249, but should fix
the failure from
https://github.com/breadboard-ai/breadboard/actions/runs/13021227644/job/36322130934

```
src/example-board-server.ts:25:30 - error TS2307: Cannot find module '@breadboard-ai/example-boards/playground-boards.json' or its corresponding type declarations.

25 import playgroundBoards from "@breadboard-ai/example-boards/playground-boards.json" assert { type: "json" };
```

cc @timswanson-google